name: Deploy JobMatch AI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repo sin credenciales automáticas
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      # 2. Setup Node.js (ajusta la versión a la que uses en tu package.json)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'   # ← cámbialo si usas otra versión
          cache: 'npm'

      # 3. Instala dependencias
      - name: Install dependencies
        run: npm ci

      # 4. Build
      - name: Build
        run: npm run build

      # 5. Configurar identidad de Git para el commit de gh-pages
      - name: Configure Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # 6. Deploy usando gh-pages y tu PAT
      - name: Deploy to GitHub Pages
        env:
          GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
        run: |
          npx gh-pages -d build \
            -r https://x-access-token:${GH_PAGES_TOKEN}@github.com/${{ github.repository }}.git

